<a href="https://colab.research.google.com/github/summer1278/UoM-NLP-student-homework/blob/main/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# take the matrix in Q1 into python
M = [[1,1,0,0],
     [1,1,0,0],
     [0,0,1,1],
     [0,0,1,1],
     [1,1,0,1]]

In [ ]:
import numpy as np
from numpy.linalg import svd,matrix_rank

In [ ]:
u,s,v = svd(M)

In [ ]:
u

array([[-4.80868748e-01, -3.16227766e-01, -4.10810477e-01,
         7.06536343e-01, -2.83971044e-02],
       [-4.80868748e-01, -3.16227766e-01, -4.10810477e-01,
        -7.06536343e-01,  2.83971044e-02],
       [-2.40434374e-01,  6.32455532e-01, -2.05405238e-01,
         2.83971044e-02,  7.06536343e-01],
       [-2.40434374e-01,  6.32455532e-01, -2.05405238e-01,
        -2.83971044e-02, -7.06536343e-01],
       [-6.49548396e-01,  1.12933584e-16,  7.60320249e-01,
         3.21230134e-16, -4.28154385e-17]])

In [ ]:
s # singular values

array([2.58873755e+00, 2.00000000e+00, 5.46294684e-01, 2.58347579e-17])

In [ ]:
v

array([[-6.22421492e-01, -6.22421492e-01, -1.85754151e-01,
        -4.36667341e-01],
       [-3.16227766e-01, -3.16227766e-01,  6.32455532e-01,
         6.32455532e-01],
       [-1.12211790e-01, -1.12211790e-01, -7.51994279e-01,
         6.39782489e-01],
       [-7.07106781e-01,  7.07106781e-01,  2.78693431e-17,
        -1.23559868e-16]])

In [ ]:
k = matrix_rank(M)
k

3

In [ ]:
# based on the rank k = 3, we will take top 3 left and right singular vectors
U = u[:,:k]
U

array([[-4.80868748e-01, -3.16227766e-01, -4.10810477e-01],
       [-4.80868748e-01, -3.16227766e-01, -4.10810477e-01],
       [-2.40434374e-01,  6.32455532e-01, -2.05405238e-01],
       [-2.40434374e-01,  6.32455532e-01, -2.05405238e-01],
       [-6.49548396e-01,  1.12933584e-16,  7.60320249e-01]])

In [ ]:
S = np.diag(s)[:k,:k]
S

array([[2.58873755, 0.        , 0.        ],
       [0.        , 2.        , 0.        ],
       [0.        , 0.        , 0.54629468]])

In [ ]:
V = v[:,:k]
V

array([[-6.22421492e-01, -6.22421492e-01, -1.85754151e-01],
       [-3.16227766e-01, -3.16227766e-01,  6.32455532e-01],
       [-1.12211790e-01, -1.12211790e-01, -7.51994279e-01],
       [-7.07106781e-01,  7.07106781e-01,  2.78693431e-17]])

In [ ]:
# term vectors
dense_term = np.matmul(V,S)
dense_term

array([[-1.61128589e+00, -1.24484298e+00, -1.01476505e-01],
       [-8.18630693e-01, -6.32455532e-01,  3.45507095e-01],
       [-2.90486874e-01, -2.24423579e-01, -4.10810477e-01],
       [-1.83051388e+00,  1.41421356e+00,  1.52248740e-17]])

In [ ]:
# document vectors
dense_doc = np.matmul(U,S)
dense_doc

array([[-1.24484298e+00, -6.32455532e-01, -2.24423579e-01],
       [-1.24484298e+00, -6.32455532e-01, -2.24423579e-01],
       [-6.22421492e-01,  1.26491106e+00, -1.12211790e-01],
       [-6.22421492e-01,  1.26491106e+00, -1.12211790e-01],
       [-1.68151033e+00,  2.25867167e-16,  4.15358910e-01]])

In [ ]:
# let's implement the cosine similarity function
from numpy import dot
from numpy.linalg import norm
def cos_sim(a, b):
  return dot(a, b)/(norm(a)*norm(b))

In [ ]:
# get the term vector for each term index
# matrix 
v_matrix = dense_term[0]
v_matrix

array([-1.61128589, -1.24484298, -0.10147651])

In [ ]:
# factorization
v_factorization = dense_term[1]
v_factorization

array([-0.81863069, -0.63245553,  0.34550709])

In [ ]:
# processing
v_processing = dense_term[3]
v_processing

array([-1.83051388e+00,  1.41421356e+00,  1.52248740e-17])

In [ ]:
# natural language
v_nl = dense_term[2]
v_nl

array([-0.29048687, -0.22442358, -0.41081048])

In [ ]:
cos_sim(v_matrix,v_factorization)

0.9315521525428485

In [ ]:
cos_sim(v_matrix,v_processing)

0.25213265791673073

In [ ]:
cos_sim(v_matrix,v_nl)

0.7025955457771914